package jgarage;

import java.sql.*; 
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 20/11/2012
//  @ Author : 
//
//

/** */
public class Client
{
    /* Variable d'instances */	
    private Integer id;		
    private String nom;	
    private String prenom;	
    private String adresse;	
    private String email;

    public Client()
    {
        this.id = 0;
        this.nom = "Inconnu";
        this.prenom = "Inconnu";
        this.adresse = "Inconnu";
        this.email = "Inconnu";
    }
    public Client(Integer id, String nom, String prenom, String adresse, String email)
    {
            this.id = id;
            this.nom = nom;
            this.prenom = prenom;
            this.adresse = adresse;
            this.email = email;	
    }    
    //*************   ACCESSEURS ************* 

    /* Retourne l'id du client 
     * @return  Integer : id du client
     */
    public Integer getId()
    {
            return this.id;
    }

    /* Retourne le nom du client
     * @return   String : nom du client
     */
    public String getNom()
    {
            return this.nom;
    }

    /* Retourne le prénom du client 
     * @return   String : prénom du client
     */
    public String getPrenom()
    {
            return this.prenom;
    }

    /* Retourne l'adresse du client 
     * @return   String : adresse du client
     */
    public String getAdresse()
    {
            return this.adresse;
    }

    /* Retourne l'adresse e-mail du client
     * @return   String : email du client
     */
    public String getEmail()
    {
            return this.email;
     }


    //*************   MUTATEURS *************

    //Définit le nom du client
    public void setNom(String nom)
    {
            this.nom = nom;
    }

    //Définit le prénom du client
    public void setPrenom(String prenom)
    {
            this.prenom = prenom;
    }

    //Définit l'adresse du client
    public void setAdresse(String adresse)
    {
            this.adresse = adresse;
    } 

    //Définit l'email du client
    public void setEmail(String email)
    {
            this.email = email;
    }

    /**
     * Méthode toString
     * @return 
     */
    public String toString() {
        return "Je suis " + this.getPrenom() + " " + this.getNom() + " (" + 
                this.getEmail() + "). \nJ'habite à " + getAdresse() + ".";
    }
    
    
}
