package jgarage;

//

import java.util.ArrayList;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Facture.java
//  @ Date : 20/11/2012
//  @ Author : 
//
//

/** */
public class Facture
{
	
	private int id;		
	private String date;
	private Float montant;
	private ArrayList<Intervention> listeIntervention;        
        
        public Facture()
        {
            this.id=0;
            this.date="Inconnu";
            this.montant=0.0f;
            listeIntervention = new ArrayList<Intervention>();
        }
        
        public Facture(int id,String date,Float montant)
        {
            this.id=id;
            this.date=date;
            this.montant=montant;
            listeIntervention = new ArrayList<Intervention>();
        }
		
	/**
        * Envoi de la facture au client par email
        * @param    
        * @return   
	*/
	public void envoyerMail()
	{  
            
           
        } 
        
        public int getId()
        {
            return this.id;
        }
        
        public String getDate()
        {
            return this.date;
        }
        
        public Float getMontant()
        {
            return this.montant;
        }      
}
