package jgarage;
//  Generated by StarUML(tm) Java Add-In
//


//  @ Project : Untitled
//  @ File Name : Vehicule.java
//  @ Date : 20/11/2012
//  @ Author : 
//
//




/** */
public class Vehicule
{
    private int idVehicule;
    private int idClient;
    /** Permet de stocker l'immatriculation du véhicule */
    private String immatriculation;	
    /** Permet de stocker la marque du véhicule */
    private String marque;	
    /** Permet de stocker le modèle du véhicule */
    private String modele;
    private String type;
    /** Permet de stocker la couleur du véhicule */
    private String couleur;	
    /** Permet de stocker le kilométrage du véhicule */
    private int nb_kilometre;	
    /** Permet de stocker le nombre de place du véhicule */
    private int nb_place;	
    /** Permet de stocker l'année du vehicule */
    private int annee;	
    /** Permet de stocker la photo d'un véhicule */
    private String photo;   

    
    public Vehicule()
    {
        this.idVehicule = 0;
        this.immatriculation = "Inconnu";
        this.marque = "Inconnu";
        this.modele = "Inconnu";
        this.type = "Inconnu";
        this.couleur = "Inconnu";
        this.nb_kilometre = 0;
        this.nb_place = 0;
        this.annee = 0;
        this.photo = "Inconnu";
    }
    public Vehicule(int idVehicule,int idClient,String immatriculation,String marque, String modele, String type, String couleur, int nb_kilometre, int nb_place, int annee, String photo)
    {
        /** On initialise toutes les variables avec les paramètres */
        this.idClient = idClient;
        this.idVehicule = idVehicule;
        this.immatriculation = immatriculation;
        this.marque = marque;
        this.modele = modele;
        this.type = type;
        this.couleur = couleur;
        this.nb_kilometre = nb_kilometre;
        this.nb_place = nb_place;
        this.annee = annee;
        this.photo = photo;

    }
     /** Permet d'ajouter une photo à un véhicule*/
    public void ajouterPhoto()
    {

    }
    
    /* Getter */
    public String getType() {
        return type;
    }    
    
    public int getId()
    {
        return idVehicule;
    }
    public int getIdClient()
    {
        return idClient;
    }
    public String getImmat() {
        return immatriculation;
    }
    
    public String getMarque() {
        return marque;
    }

    public String getModele() {
        return modele;
    }

    public String getCouleur() {
        return couleur;
    }

    public int getNb_kilometre() {
        return nb_kilometre;
    }

    public int getNb_place() {
        return nb_place;
    }

    public int getAnnee() {
        return annee;
    }

    public String getPhoto() {
        return photo;
    }       
    
}
